"""
Delivery ASAP hub — application package.

Layers, each with one reason to change:

    settings     deployment configuration (settings.toml) + presentation constants
    frontmatter  YAML front matter of the markdown cards ⇄ Python data
    repository   the knowledge vault on disk (the only I/O)
    domain       dates, tiers, roles, gantt parsing, timeline calendar (pure)
    schema       the project card schema, declared once
    markup       HTML escaping primitives
    gantt        chart rendering
    view         page and detail panel rendering
    api          mutations, exposed through a routing table
    server       HTTP, static assets, JSON
    static/      app.css and app.js — real files, never generated by Python
"""

__version__ = '1.0.0'
